### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by amandalal007** [prokunal/Smart-Youtube-Playlist-Downloader#1]
Brother i am using this thing from many days its actually great  but it only downloads 720p please add 1080p and 4k if possible but plz. try to add 1080p

**Comment by prokunal** [comment]
@amandalal123 i thought about it, but every video is not in 1080p or 720p or 4k.
Imagine if you choose resolution of 1080p to download the all video, if any video have highest of 720p resolution, then it will throw an error, and file will not be downloaded. it will be hard to identify for user which file is not downloaded.

Thanks

**Comment by amandalal007** [comment]
Brother thanks for reply by the way can you possibley add an option to choose quality 
By the way love u...

**Comment by prokunal** [comment]
Hello @amandalal123

I add the feature to choose resolution for your download, now, you can select resolution to download the videos in specific resolution like: 480p, 720p, 1080p, 2160p(4k).

If you really like this script, feel free to give me a star.

Thanks
