### ISSUE TITLE
bhai 1080p aur 4k me sound nahi hot kya ????

### ISSUE THREAD

**Issue by amandalal007** [prokunal/Smart-Youtube-Playlist-Downloader#3]

**Comment by prokunal** [comment]
Sorry for this issue, i am working on it, it will take some times.
actually pytube doesn't support to download video and audio of highest quality, it works good for 720p.
Give me sometime, i will try to find a way to fix this issue.

Thanks

**Comment by amandalal007** [comment]
no problem brother i am happy even with 720p just take your time i will be looking ahead

**Comment by prokunal** [comment]
I found some way to do it, but it is very time consuming for end user, for now i am removing the resolution selection feature.
