### ISSUE TITLE
Missing Exception handling crashes threads

### ISSUE THREAD

**Issue by six-two** [prokunal/Smart-Youtube-Playlist-Downloader#4]
Hi,

I just tried your script and wanted to thank you for it. It works pretty well, but downloading a playlist with some age restricted videos, I saw the following error message:
```
Exception in thread d3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/Smart-Youtube-Playlist-Downloader/yt_playlist_downloader.py", line 49, in downloader3
    ys = yt.streams.get_highest_resolution()
         ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 264, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
```

My problems:
1. It would be nice to show a message which video was affected, so that I could download it manually.
2. This crashed the whole thread. If I read the code correctly this means that all other videos queued for that thread will not be downloaded and after 4 crashes there will be no threads left.

Suggested fix: Change the download methods to something like this that handles any errors in the for loop:
```python
def downloader1():
    for i in link[0]:
      try:
        yt = YouTube(i)
        ys = yt.streams.get_highest_resolution()
        filename = ys.download()
        print("threading 1 -->  " + filename.split('/')[-1] + ' Downloaded')
      except Exception as e:
        print(f"Failed to download {i}: {e}")
```

**Comment by prokunal** [comment]
Thank you for bringing up the issue, I resolved the issue, you can now try again.

**Comment by six-two** [comment]
Hi, that was quick! :+1:  I would put the exception handling inside the `for` loop, otherwise the thread will still stop working after the first error.

For testing this playlist may be useful: https://www.youtube.com/playlist?list=PLhvYClM7zqclqWmWx6oiQdqkbtfUt9k-W

**Comment by prokunal** [comment]
Hello, Thank you for pointing out the issue again, when i was updating the script in my mind, thing was same as you mentioned earlier, but somehow i forgot to do that, and added exception handling outside the loop.
I have updated the code now.
